import type { GaneshReport } from "@/shared/utils/ganeshReportBuilder";

/**
 * Rendering a report as CSV and as printable HTML (GS-079).
 *
 * Both take the same `GaneshReport` and format it — neither computes a figure,
 * so the two can never disagree about a total.
 */

/* ------------------------------------------------------------------ *
 * CSV — for a spreadsheet
 * ------------------------------------------------------------------ */

/** RFC-4180. */
function csvField(value: unknown): string {
  if (value === null || value === undefined) return "";
  const text = String(value);
  if (/[",\n\r]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
  return text;
}

function csvRow(cells: unknown[]): string {
  return cells.map(csvField).join(",");
}

/**
 * Transaction-level CSV, with the report's own context in the file.
 *
 * The preamble matters: a bare grid of numbers on someone's laptop three months
 * later cannot be checked against anything. Which Pandal, which festival, which
 * dates and who exported it all travel with the data — and a spreadsheet
 * ignores the leading lines happily enough.
 */
export function reportToCsv(report: GaneshReport): string {
  const lines: string[] = [];

  lines.push(csvRow(["Ganesh Seva - financial report"]));
  lines.push(csvRow(["Pandal", report.pandalName]));
  lines.push(
    csvRow([
      "Festival",
      report.festivalYear ? `${report.festivalName} ${report.festivalYear}` : report.festivalName,
    ])
  );
  lines.push(csvRow(["Date range", report.range.label]));
  lines.push(csvRow(["Generated", report.generatedAt]));
  lines.push(csvRow(["Generated by", report.generatedBy]));
  for (const warning of report.warnings) lines.push(csvRow(["Warning", warning]));
  lines.push("");

  lines.push(csvRow(["Summary"]));
  lines.push(csvRow(["Opening funds", report.summary.openingFunds]));
  lines.push(csvRow(["Collections", report.summary.collections]));
  lines.push(csvRow(["Contributions received", report.summary.contributions]));
  lines.push(csvRow(["Expenses", report.summary.expenses]));
  lines.push(csvRow(["Reimbursements", report.summary.reimbursements]));
  lines.push(csvRow(["Transfers in (from Permanent Fund)", report.summary.transfersIn]));
  lines.push(csvRow(["Transfers out (to Permanent Fund)", report.summary.transfersOut]));
  lines.push(csvRow(["Closing balance", report.summary.closingBalance]));
  lines.push(csvRow(["Promised, not yet received", report.summary.promisedOutstanding]));
  if (report.summary.partialRange) {
    lines.push(
      csvRow([
        "Note",
        "These totals cover the selected date range only, not the whole festival.",
      ])
    );
  }
  lines.push("");

  lines.push(csvRow(["Transactions"]));
  lines.push(
    csvRow([
      "Date",
      "Type",
      "Purpose",
      "Description",
      "Amount",
      "Direction",
      "Payment method",
      "Recorded by",
      "Reference",
      "Purpose source",
    ])
  );
  for (const row of report.transactions) {
    lines.push(
      csvRow([
        row.date,
        row.type,
        row.purpose,
        row.description,
        row.amount,
        row.direction,
        row.paymentMethod,
        row.person,
        row.reference,
        // Flagged so an analyst does not treat a derived classification as one
        // somebody chose.
        row.legacyPurpose ? "derived (recorded before purposes existed)" : "recorded",
      ])
    );
  }

  if (report.collections.included && report.collections.rows.length > 0) {
    lines.push("");
    lines.push(csvRow(["Collections detail"]));
    lines.push(
      csvRow(["Date", "Donor", "Amount", "Payment method", "Collector", "Session", "Area", "Receipt"])
    );
    for (const row of report.collections.rows) {
      lines.push(
        csvRow([
          row.date,
          row.donorName,
          row.amount,
          row.paymentMethod,
          row.collector,
          row.session,
          row.area,
          row.receipt,
        ])
      );
    }
  }

  if (report.reconciliations.included && report.reconciliations.rows.length > 0) {
    lines.push("");
    lines.push(csvRow(["Cash reconciliation"]));
    lines.push(
      csvRow([
        "Date",
        "Collector",
        "Expected cash",
        "Counted cash",
        "Difference",
        "Status",
        "Counted by",
        "Approved by",
      ])
    );
    for (const row of report.reconciliations.rows) {
      lines.push(
        csvRow([
          row.date,
          row.collector,
          row.expectedCash,
          row.countedCash,
          row.difference,
          row.status,
          row.countedBy,
          row.approvedBy,
        ])
      );
    }
  }

  return lines.join("\r\n");
}

/* ------------------------------------------------------------------ *
 * HTML — for the PDF
 * ------------------------------------------------------------------ */

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function inr(value: number): string {
  const rounded = Math.round(Number(value ?? 0) * 100) / 100;
  return `₹${rounded.toLocaleString("en-IN")}`;
}

function table(headers: string[], rows: Array<Array<string | number>>): string {
  if (rows.length === 0) return "<p class='empty'>Nothing recorded in this range.</p>";
  return `<table>
  <thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead>
  <tbody>${rows
    .map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`)
    .join("")}</tbody>
</table>`;
}

/**
 * A report a committee can read out, not a screenshot of the app.
 *
 * Printed in the order a hisab is actually presented: what came in, what went
 * out, what is left, and then the detail behind it. Discrepancy warnings go at
 * the **top**, before the totals — a mismatch discovered on page three, after
 * the numbers have been read aloud, is a mismatch that has already misled
 * everyone in the room.
 */
export function reportToHtml(report: GaneshReport): string {
  const s = report.summary;
  const title = report.festivalYear
    ? `${report.festivalName} ${report.festivalYear}`
    : report.festivalName;

  const warnings = report.warnings.length
    ? `<div class="warn"><strong>Please note</strong><ul>${report.warnings
        .map((w) => `<li>${escapeHtml(w)}</li>`)
        .join("")}</ul></div>`
    : "";

  return `<!doctype html>
<html><head><meta charset="utf-8" />
<style>
  body { font-family: -apple-system, Roboto, sans-serif; color: #2b1a12; padding: 28px; }
  h1 { font-size: 21px; margin: 0 0 2px; color: #7b2d12; }
  h2 { font-size: 15px; margin: 22px 0 8px; color: #7b2d12;
       border-bottom: 1px solid #e8d8c8; padding-bottom: 4px; }
  .sub { color: #6b5748; font-size: 12.5px; margin: 0 0 2px; }
  .warn { background: #fdf0e6; border: 1px solid #e4a672; border-radius: 8px;
          padding: 10px 14px; margin: 16px 0; font-size: 12.5px; }
  .warn ul { margin: 6px 0 0 18px; padding: 0; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 6px; }
  th { text-align: left; background: #faf3ec; padding: 6px 8px; border-bottom: 1px solid #e8d8c8; }
  td { padding: 6px 8px; border-bottom: 1px solid #f2e8de; }
  .totals td { font-size: 13px; padding: 5px 8px; }
  .totals .k { color: #6b5748; }
  .totals .v { text-align: right; font-weight: 600; }
  .closing { border-top: 2px solid #7b2d12; }
  .empty { color: #8a7566; font-size: 12.5px; font-style: italic; }
  .foot { margin-top: 26px; color: #8a7566; font-size: 11px; }
</style></head>
<body>
  <h1>${escapeHtml(report.pandalName)}</h1>
  <p class="sub">${escapeHtml(title)} — financial report</p>
  <p class="sub">Covering: <strong>${escapeHtml(report.range.label)}</strong></p>

  ${warnings}

  <h2>Summary</h2>
  <table class="totals">
    <tr><td class="k">Opening funds</td><td class="v">${inr(s.openingFunds)}</td></tr>
    <tr><td class="k">Collections</td><td class="v">${inr(s.collections)}</td></tr>
    <tr><td class="k">Contributions received</td><td class="v">${inr(s.contributions)}</td></tr>
    <tr><td class="k">Expenses</td><td class="v">-${inr(s.expenses)}</td></tr>
    <tr><td class="k">Reimbursements</td><td class="v">-${inr(s.reimbursements)}</td></tr>
    <tr><td class="k">Transfers in, from the Permanent Fund</td>
        <td class="v">${inr(s.transfersIn)}</td></tr>
    <tr><td class="k">Transfers out, to the Permanent Fund</td>
        <td class="v">-${inr(s.transfersOut)}</td></tr>
    <tr class="closing"><td class="k"><strong>Closing balance</strong></td>
        <td class="v">${inr(s.closingBalance)}</td></tr>
    <tr><td class="k">Promised, not yet received</td>
        <td class="v">${inr(s.promisedOutstanding)}</td></tr>
  </table>
  ${
    s.partialRange
      ? `<p class="sub">These totals cover the selected range only, not the whole festival.</p>`
      : ""
  }

  <h2>Cash reconciliation</h2>
  ${
    report.reconciliations.included
      ? table(
          ["Date", "Collector", "Expected", "Counted", "Difference", "Status", "Approved by"],
          report.reconciliations.rows.map((r) => [
            r.date,
            r.collector,
            inr(r.expectedCash),
            inr(r.countedCash),
            inr(r.difference),
            r.status,
            r.approvedBy || "—",
          ])
        )
      : `<p class="empty">Not included — your role cannot view cash reconciliation.</p>`
  }

  <h2>Collections</h2>
  ${
    report.collections.included
      ? table(
          ["Date", "Donor", "Amount", "Method", "Collector", "Area"],
          report.collections.rows.map((r) => [
            r.date,
            r.donorName,
            inr(r.amount),
            r.paymentMethod,
            r.collector,
            r.area || "—",
          ])
        )
      : `<p class="empty">Not included — your role cannot view collections.</p>`
  }

  <h2>Expenses</h2>
  ${
    report.expenses.included
      ? table(
          ["Date", "What", "Purpose", "Vendor", "Amount", "Method", "Recorded by"],
          report.expenses.rows.map((r) => [
            r.date,
            r.name,
            r.purpose,
            r.vendor || "—",
            inr(r.amount),
            r.paymentMethod,
            r.createdBy,
          ])
        )
      : `<p class="empty">Not included — your role cannot view expenses.</p>`
  }

  <p class="foot">
    Generated ${escapeHtml(report.generatedAt)} by ${escapeHtml(report.generatedBy)}.
  </p>
</body></html>`;
}

/** A filename that says what it is without being opened. */
export function reportFileName(report: GaneshReport, extension: "csv" | "pdf"): string {
  const safe = (value: string) => value.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "");
  const stamp = report.generatedAt.slice(0, 10);
  return `${safe(report.pandalName)}-${safe(report.range.label)}-${stamp}.${extension}`;
}
