// Generates a local .env for Cloud Agent / sandbox use from values that already
// live in the repository. The Firebase web config is read from the committed
// google-services.json; the README documents that these EXPO_PUBLIC_FIREBASE_*
// values are non-secret and are embedded in every shipped APK. No signing
// passwords or server-only secrets are ever written here.
//
// Skips writing if a .env already exists, so it is safe to run repeatedly.
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");

if (fs.existsSync(ENV_PATH)) {
  console.log(".env already exists; not overwriting.");
  process.exit(0);
}

const gsPath = path.join(ROOT, "google-services.json");
const gs = JSON.parse(fs.readFileSync(gsPath, "utf8"));

const projectId = gs.project_info.project_id;
const messagingSender = gs.project_info.project_number;
const storageBucket = gs.project_info.storage_bucket;

// Prefer the client whose package matches the main app; fall back to the first.
const mainClient =
  gs.client.find(
    (c) => c.client_info.android_client_info.package_name === "com.example.expensetracker"
  ) || gs.client[0];

const apiKey = mainClient.api_key[0].current_key;
const appId = mainClient.client_info.mobilesdk_app_id;

// OAuth "web" client (client_type 3) drives Google Sign-In ID tokens.
const webOauth = mainClient.oauth_client.find((o) => o.client_type === 3);
const googleWebClientId = webOauth ? webOauth.client_id : "";

const lines = [
  "# Auto-generated by .cursor/generate-env.js for the Cloud Agent sandbox.",
  "# Firebase values are the non-secret config from google-services.json.",
  "EXPO_PUBLIC_SHARE_URL=https://spendly-share.netlify.app",
  "EXPO_PUBLIC_APP_URL=https://kesavaexpensetracker.netlify.app",
  "",
  `EXPO_PUBLIC_FIREBASE_API_KEY=${apiKey}`,
  `EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${projectId}.firebaseapp.com`,
  `EXPO_PUBLIC_FIREBASE_PROJECT_ID=${projectId}`,
  `EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${storageBucket}`,
  `EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER=${messagingSender}`,
  `EXPO_PUBLIC_FIREBASE_APP_ID=${appId}`,
  "",
  `EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${googleWebClientId}`,
  "",
  "MYAPP_RELEASE_STORE_PASSWORD=",
  "MYAPP_RELEASE_KEY_PASSWORD=",
  "",
].join("\n");

fs.writeFileSync(ENV_PATH, lines);
console.log(`Wrote ${ENV_PATH} for project "${projectId}".`);
