const fs = require("fs");
const path = require("path");
const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");

/**
 * SPENDLY-175: the Firebase Local Emulator Suite speaks plain http, and an
 * Android release build refuses cleartext traffic by default. Firestore's
 * WebChannel then fails with "transport errored" even though the emulator is
 * reachable. This plugin lets the local test app ("Spendly Test") use http
 * for the emulator host ONLY, through a network security config. Every other
 * host stays https-only.
 *
 * Registered solely by applyLocalTestBuild in app.config.js, so the real app
 * never includes it.
 */
const XML_NAME = "spendly_local_test_network_security";

function networkSecurityXml(hosts) {
  const domains = hosts
    .map((host) => `        <domain includeSubdomains="false">${host}</domain>`)
    .join("\n");
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withLocalTestCleartext.js (SPENDLY-175). -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
${domains}
    </domain-config>
</network-security-config>
`;
}

module.exports = function withLocalTestCleartext(config, { host }) {
  // 127.0.0.1 and localhost both reach the PC through `adb reverse`.
  const hosts = [...new Set([host, "127.0.0.1", "localhost"])];

  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res", "xml");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${XML_NAME}.xml`), networkSecurityXml(hosts));
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (application) {
      application.$["android:networkSecurityConfig"] = `@xml/${XML_NAME}`;
    }
    return cfg;
  });
};

module.exports.networkSecurityXml = networkSecurityXml;
