name: Test Caller (temp)

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      mandatory:
        required: false
        default: false
        type: boolean
      notes:
        required: false
        type: string

permissions:
  contents: write

jobs:
  call:
    uses: ./.github/workflows/test-reusable.yml
    with:
      product: expense
      version: ${{ inputs.version }}
      mandatory: ${{ inputs.mandatory }}
      notes: ${{ inputs.notes }}
    secrets: inherit
